//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLR_Taules_Menu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestioUsuarisEntities : DbContext
    {
        public GestioUsuarisEntities()
            : base("name=GestioUsuarisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filiation> Filiations { get; set; }
        public virtual DbSet<Planet> Planets { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<UserCategory> UserCategories { get; set; }
        public virtual DbSet<UserRank> UserRanks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
